/partol_node:
  ros__parameters:
    initial_point: [0.0, 0.0, 0.0]
    target_points: [
      0.0, 0.0, 0.0,
      2.0, 4.0, 3.14,
      -5.0, 4.5, 1.57,
      1.0, -3.0, 3.14,
      4.0, -4.0, 3.14
    ]
    use_sim_time: false