controller_manager:
  ros__parameters:
    update_rate: 100  # Hz
    use_sim_time: true
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
      use_sim_time: true
    car_effort_controller:
      type: effort_controllers/JointGroupEffortController
    car_diff_drive_controller:
      type: diff_drive_controller/DiffDriveController

car_effort_controller:
  ros__parameters:
    joints:
      - front_left2base_link
      - front_right2base_link
    command_interfaces:
      - effort
    state_interfaces:
      - position
      - velocity
      - effort



car_diff_drive_controller:
  ros__parameters:
    left_wheel_names: ["front_left2base_link"]
    right_wheel_names: ["front_right2base_link"]

    wheel_separation: 0.20
    #wheels_per_side: 1  # actually 2, but both are controlled by 1 signal
    wheel_radius: 0.025

    wheel_separation_multiplier: 1.0
    left_wheel_radius_multiplier: 1.0
    right_wheel_radius_multiplier: 1.0

    publish_rate: 50.0
    odom_frame_id: odom
    base_frame_id: base_footprint
    pose_covariance_diagonal : [0.001, 0.001, 0.0, 0.0, 0.0, 0.01]
    twist_covariance_diagonal: [0.001, 0.0, 0.0, 0.0, 0.0, 0.01]

    open_loop: true
    enable_odom_tf: true

    cmd_vel_timeout: 0.5
    #publish_limited_velocity: true
    use_stamped_vel: false
    #velocity_rolling_window_size: 10